[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter growfit-shared build --no-deps',
  'pnpm --filter growfit-api build --no-deps',
  'cd apps/api && pnpm prisma:generate',
  'mkdir -p apps/api/node_modules/growfit-shared',

]

[start]
cmd = 'cd apps/api && pnpm prisma:migrate deploy && pnpm start:prod'
