[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter growfit-shared build',
  'pnpm --filter growfit-api build',
  'cd apps/api && pnpm prisma:generate',
  'ls -la packages/shared/dist || echo "Shared dist not found"',
  'ls -la node_modules/growfit-shared || echo "Shared in node_modules not found"'
]

[start]
cmd = 'cd apps/api && pnpm prisma:migrate deploy && pnpm start:prod'
