[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install && pnpm --filter growfit-shared build && pnpm --filter growfit-api build && cd apps/api && pnpm prisma:generate"

[deploy]
startCommand = "cd apps/api && pnpm prisma:migrate deploy && node dist/apps/api/src/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
